### ISSUE TITLE
AttributeError: 'GuidedTranslationTask' object has no attribute 'args'

### ISSUE THREAD

**Issue by SONGPENG** [neulab/guided_summarization#14]
2021-06-10 00:18:28 | INFO | fairseq_cli.train | task: GuidedTranslationTask
2021-06-10 00:18:28 | INFO | fairseq_cli.train | model: GuidedBARTModel
2021-06-10 00:18:28 | INFO | fairseq_cli.train | criterion: LabelSmoothedCrossEntropyCriterion
2021-06-10 00:18:28 | INFO | fairseq_cli.train | num. shared model params: 469,292,032 (num. trained: 469,292,032)
2021-06-10 00:18:28 | INFO | fairseq_cli.train | num. expert model params: 0 (num. trained: 0)
Traceback (most recent call last):
  File "/home/songpeng/.conda/envs/fairseq/bin/fairseq-train", line 33, in <module>
    sys.exit(load_entry_point('fairseq', 'console_scripts', 'fairseq-train')())
  File "/data/songpeng/project_my/fairseq/fairseq_cli/train.py", line 507, in cli_main
    distributed_utils.call_main(cfg, main)
  File "/data/songpeng/project_my/fairseq/fairseq/distributed/utils.py", line 369, in call_main
    main(cfg, **kwargs)
  File "/data/songpeng/project_my/fairseq/fairseq_cli/train.py", line 124, in main
    task.load_dataset(valid_sub_split, combine=False, epoch=1)
  File "/data/songpeng/project_my/fairseq/fairseq/tasks/guided_translation.py", line 253, in load_dataset
    paths = utils.split_paths(self.args.data)
AttributeError: 'GuidedTranslationTask' object has no attribute 'args'

**Comment by zdou0830** [comment]
Hi, just to confirm, what is the commit number of your fairseq? is it c699eb054e2782e2ae4e1d85d1fff5a724dc5c0e?

**Comment by SONGPENG** [comment]
Thanks for your reply. How can I get the commit number ?
Should I use `git log` ？

**Comment by zdou0830** [comment]
Yes, as I mentioned in our previous discussion, you should try to install c699eb054e2782e2ae4e1d85d1fff5a724dc5c0e of fairseq instead of the latest version.

You can do `git reset --hard c699eb054e2782e2ae4e1d85d1fff5a724dc5c0e` and then do `pip install --editable .` to see if you can install the fairseq correctly. If it fails, this is an issue of fairseq and I would suggest you to look into their repo. Please do not just migrate our added files into a different version of fairseq.

**Comment by SONGPENG** [comment]
Finally, I solve the problem following
1) I first install [fairseq](https://github.com/pytorch/fairseq) then run `git reset --hard c699eb054e2782e2ae4e1d85d1fff5a724dc5c0e` and `pip install --editable ./`
2) Afterwards, I still migrate your added files into this fairseq. (I have to do so, because I cannot directly use `pip install --editable ./` in your repo )

Finally, It works.......

All in all, very thanks your swift and patient reply.

**Comment by zdou0830** [comment]
Note that the added files aren't the only files I changed. If you want to do the migration, please compare all the files between the two repos.
