### ISSUE TITLE
can't test when on bart

### ISSUE THREAD

**Issue by gaozhiguang** [neulab/guided_summarization#19]
Hi, thanks for the nice work.
when i tried to follow the instructions to predict using the provided model, i have such an error:

(testtransformers) [zggao@cu05 bart]$ bash z_test.sh  ./cnn_dm/test.source   ./bart_sentence_guide_cnndm/test.matchsum cnndm.test.output   ./    bart_sentence.pt   cnndm-bin-z
Traceback (most recent call last):
  File "z_test.py", line 8, in <module>
    data_name_or_path=sys.argv[6]
  File "/home/zggao/document-summarization/GSum/guided_summarization-master/bart/fairseq/models/bart/guided_model.py", line 169, in from_pretrained
    **kwargs,
  File "/home/zggao/document-summarization/GSum/guided_summarization-master/bart/fairseq/hub_utils.py", line 73, in from_pretrained
    arg_overrides=kwargs,
  File "/home/zggao/document-summarization/GSum/guided_summarization-master/bart/fairseq/checkpoint_utils.py", line 200, in load_model_ensemble_and_task
    task = tasks.setup_task(args)
  File "/home/zggao/document-summarization/GSum/guided_summarization-master/bart/fairseq/tasks/__init__.py", line 17, in setup_task
    return TASK_REGISTRY[args.task].setup_task(args, **kwargs)
  File "/home/zggao/document-summarization/GSum/guided_summarization-master/bart/fairseq/tasks/guided_translation.py", line 227, in setup_task
    paths = utils.split_paths(args.data)
  File "/home/zggao/document-summarization/GSum/guided_summarization-master/bart/fairseq/utils.py", line 30, in split_paths
    return paths.split(os.pathsep) if "://" not in paths else paths.split("|")
TypeError: argument of type 'NoneType' is not iterable

**Comment by zdou0830** [comment]
Hi, it seems that there is an extra space in the model path "./ bart_sentence.pt'

**Comment by gaozhiguang** [comment]
Hi, Thanks for the reply.
In addition to the above problems, it seems that the sixth parameter should be changed to the bin file directory.

**Comment by zdou0830** [comment]
Yes, please follow the README to set the arguments.

**Comment by lakshmi-imrsv** [comment]
I am also getting the same error 
in split_paths
return paths.split(os.pathsep) if "://" not in paths else paths.split("|")
TypeError: argument of type 'NoneType' is not iterable
@gaozhiguang  how did you resolve this?
