### ISSUE TITLE
file2rouge problem

### ISSUE THREAD

**Issue by gaozhiguang** [neulab/guided_summarization#20]
Hi, when using file2rouge, i met this issue, do you konw how to fix it?

(testtransformers) [zggao@cu05 result]$ files2rouge test.hypo.tokenized test.target.tokenized 
Preparing documents... 0 line(s) ignored
Running ROUGE...
Traceback (most recent call last):
  File "/home/zggao/anaconda3/envs/testtransformers/bin/files2rouge", line 33, in <module>
    sys.exit(load_entry_point('files2rouge==2.1.0', 'console_scripts', 'files2rouge')())
  File "/home/zggao/anaconda3/envs/testtransformers/lib/python3.6/site-packages/files2rouge-2.1.0-py3.6.egg/files2rouge/files2rouge.py", line 105, in main
    args.stemming)
  File "/home/zggao/anaconda3/envs/testtransformers/lib/python3.6/site-packages/files2rouge-2.1.0-py3.6.egg/files2rouge/files2rouge.py", line 54, in run
    stemming=stemming)
TypeError: __init__() got an unexpected keyword argument 'log_level'

**Comment by gaozhiguang** [comment]
before installing the files2rouge, we have to install a custom pyrouge, which is different from "pip install pyrouge"
