### ISSUE TITLE
RuntimeError: masked_select(): self and result must have the same scalar type

### ISSUE THREAD

**Issue by lakshmi-imrsv** [neulab/guided_summarization#30]
Did anyone encounter this error while trying to get an inference from the pretrained model(Bart) ?

(guided2) user@user-Alienware-15-R4:~/Lakshmi/guided_summarization/bart$ bash z_test.sh test.source test.matchsum test.output our_model bart_sentence.pt /home/user/Lakshmi/guided_summarization/binarized 

Traceback (most recent call last):
  File "z_test.py", line 25, in <module>
    hypotheses_batch = bart.sample(slines, zlines, beam=4, lenpen=2.0, max_len_b=140, min_len=55, no_repeat_ngram_size=3, guided=True)
  File "/home/user/Lakshmi/guided_summarization/bart/fairseq/models/bart/guided_hub_interface.py", line 125, in sample
    hypos = self.generate(input, z, beam, verbose, **kwargs)
  File "/home/user/Lakshmi/guided_summarization/bart/fairseq/models/bart/guided_hub_interface.py", line 142, in generate
    prefix_tokens=sample['net_input']['src_tokens'].new_zeros((len(tokens), 1)).fill_(self.task.source_dictionary.bos()),
  File "/home/user/Lakshmi/guided_summarization/bart/fairseq/tasks/fairseq_task.py", line 354, in inference_step
    return generator.generate(models, sample, prefix_tokens=prefix_tokens)
  File "/home/user/anaconda3/envs/guided2/lib/python3.7/site-packages/torch/autograd/grad_mode.py", line 28, in decorate_context
    return func(*args, **kwargs)
  File "/home/user/Lakshmi/guided_summarization/bart/fairseq/sequence_generator.py", line 852, in generate
    return self._generate(model, sample, **kwargs)
  File "/home/user/anaconda3/envs/guided2/lib/python3.7/site-packages/torch/autograd/grad_mode.py", line 28, in decorate_context
    return func(*args, **kwargs)
  File "/home/user/Lakshmi/guided_summarization/bart/fairseq/sequence_generator.py", line 1146, in _generate
    out=eos_bbsz_idx,
RuntimeError: masked_select(): self and result must have the same scalar type

**Comment by lakshmi-imrsv** [comment]
Could solve the issue when I downgraded torch to version 1.5.0 
Reference : https://github.com/pytorch/fairseq/issues/2925#issue-747083118

**Comment by shakeley** [comment]
@lakshmi-imrsv Hi, I encountered the same problem as you when I run on NVIDIA 3090 with torch 1.8.0. When I downgraded torch to version 1.5.0 the training script is stuck at the very beginning as well as z_test.sh. 

Did you change anything except downgrading torch & which GPU&CUDA version did you use? 

Thanks:)

**Comment by yuping-wu** [comment]
> 

Same with NVIDIA 3090 and torch 1.8.0, solution which is provided here https://github.com/ictnlp/OR-NMT/issues/9#issuecomment-723015506 solved this issue without downgrading torch version, simply modify the line with torch.div to // in search.py. Hope it helps!

**Comment by shakeley** [comment]
> 

Thanks! It works.
