### ISSUE TITLE
Bart模型测试问题

### ISSUE THREAD

**Issue by JingAnLu** [neulab/guided_summarization#58]
请问bart的模型训练完成后，如何进行测试呢。我根据readme里面的例子传参，遇到很多参数问题，通过debug倒是改的差不多了，但是又出现request的connectionError。应该怎么修改呢？
下面是我的z_test使用pycharm parameters传参：
../../data/test.source-target.source
../../data/test.source-target.z
../../result
./trained_model/cnndm
checkpoint_best.pt
../../data

以下的报错信息：
`Traceback (most recent call last):
  File "/root/anaconda3/envs/LJA_bart/lib/python3.6/site-packages/urllib3/connectionpool.py", line 710, in urlopen
    chunked=chunked,
  File "/root/anaconda3/envs/LJA_bart/lib/python3.6/site-packages/urllib3/connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "/root/anaconda3/envs/LJA_bart/lib/python3.6/site-packages/urllib3/connectionpool.py", line 1042, in _validate_conn
    conn.connect()
  File "/root/anaconda3/envs/LJA_bart/lib/python3.6/site-packages/urllib3/connection.py", line 429, in connect
    tls_in_tls=tls_in_tls,
  File "/root/anaconda3/envs/LJA_bart/lib/python3.6/site-packages/urllib3/util/ssl_.py", line 450, in ssl_wrap_socket
    sock, context, tls_in_tls, server_hostname=server_hostname
  File "/root/anaconda3/envs/LJA_bart/lib/python3.6/site-packages/urllib3/util/ssl_.py", line 493, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "/root/anaconda3/envs/LJA_bart/lib/python3.6/ssl.py", line 407, in wrap_socket
    _context=self, _session=session)
  File "/root/anaconda3/envs/LJA_bart/lib/python3.6/ssl.py", line 817, in __init__
    self.do_handshake()
  File "/root/anaconda3/envs/LJA_bart/lib/python3.6/ssl.py", line 1077, in do_handshake
    self._sslobj.do_handshake()
  File "/root/anaconda3/envs/LJA_bart/lib/python3.6/ssl.py", line 689, in do_handshake
    self._sslobj.do_handshake()
OSError: [Errno 0] Error

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/anaconda3/envs/LJA_bart/lib/python3.6/site-packages/requests/adapters.py", line 450, in send
    timeout=timeout
  File "/root/anaconda3/envs/LJA_bart/lib/python3.6/site-packages/urllib3/connectionpool.py", line 788, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "/root/anaconda3/envs/LJA_bart/lib/python3.6/site-packages/urllib3/util/retry.py", line 550, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/root/anaconda3/envs/LJA_bart/lib/python3.6/site-packages/urllib3/packages/six.py", line 769, in reraise
    raise value.with_traceback(tb)
  File "/root/anaconda3/envs/LJA_bart/lib/python3.6/site-packages/urllib3/connectionpool.py", line 710, in urlopen
    chunked=chunked,
  File "/root/anaconda3/envs/LJA_bart/lib/python3.6/site-packages/urllib3/connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "/root/anaconda3/envs/LJA_bart/lib/python3.6/site-packages/urllib3/connectionpool.py", line 1042, in _validate_conn
    conn.connect()
  File "/root/anaconda3/envs/LJA_bart/lib/python3.6/site-packages/urllib3/connection.py", line 429, in connect
    tls_in_tls=tls_in_tls,
  File "/root/anaconda3/envs/LJA_bart/lib/python3.6/site-packages/urllib3/util/ssl_.py", line 450, in ssl_wrap_socket
    sock, context, tls_in_tls, server_hostname=server_hostname
  File "/root/anaconda3/envs/LJA_bart/lib/python3.6/site-packages/urllib3/util/ssl_.py", line 493, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "/root/anaconda3/envs/LJA_bart/lib/python3.6/ssl.py", line 407, in wrap_socket
    _context=self, _session=session)
  File "/root/anaconda3/envs/LJA_bart/lib/python3.6/ssl.py", line 817, in __init__
    self.do_handshake()
  File "/root/anaconda3/envs/LJA_bart/lib/python3.6/ssl.py", line 1077, in do_handshake
    self._sslobj.do_handshake()
  File "/root/anaconda3/envs/LJA_bart/lib/python3.6/ssl.py", line 689, in do_handshake
    self._sslobj.do_handshake()
urllib3.exceptions.ProtocolError: ('Connection aborted.', OSError(0, 'Error'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/data/private/LJA/guided_summarization/bart/fairseq/file_utils.py", line 280, in get_from_cache
    http_get(url, temp_file)
  File "/opt/data/private/LJA/guided_summarization/bart/fairseq/file_utils.py", line 219, in http_get
    req = requests.get(url, stream=True)
  File "/root/anaconda3/envs/LJA_bart/lib/python3.6/site-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/root/anaconda3/envs/LJA_bart/lib/python3.6/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/root/anaconda3/envs/LJA_bart/lib/python3.6/site-packages/requests/sessions.py", line 529, in request
    resp = self.send(prep, **send_kwargs)
  File "/root/anaconda3/envs/LJA_bart/lib/python3.6/site-packages/requests/sessions.py", line 645, in send
    r = adapter.send(request, **kwargs)
  File "/root/anaconda3/envs/LJA_bart/lib/python3.6/site-packages/requests/adapters.py", line 501, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', OSError(0, 'Error'))`

**Comment by CSgaoan** [comment]
我也是一样，加载不了，网址请求拉去失败，有没有大佬解决了的
